/*
 * The header file for X3 NV
 *
 * Copyright (C) 2011 LGE, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 */

#ifndef __MACH_TEGRA_X3_NV_H
#define __MACH_TEGRA_X3_NV_H

#define LGE_NVDATA_PARTITION			"/dev/block/platform/sdhci-tegra.3/by-name/NVA"

typedef enum{
	LGE_NVDATA_IMEI_OFFSET = 8,
	LGE_NVDATA_SWV_OFFSET = 48,
	LGE_NVDATA_MSISDN_OFFSET = 176,
	LGE_NVDATA_SWOV_OFFSET = 208,
	LGE_NVDATA_INFO_OFFSET = 336,
	
	LGE_NVDATA_REMOVE_FAT_OFFSET = 510,

	LGE_NVDATA_RESET_CAUSE_OFFSET 	= 512,
	LGE_NVDATA_CRASH_DUMP_OFFSET 	= 514,
	LGE_NVDATA_AP_CRASH_DUMP_OFFSET = 515,
	LGE_NVDATA_FORCE_CRASH_OFFSET 	= 516,

	LGE_NVDATA_FACTORY_RESET_STATUS_OFFSET 	= 518,
	LGE_NVDATA_FBOOT_OFFSET 	= 520,

	LGE_NVDATA_CP_CRASH_COUNT_OFFSET = 523,

	LGE_NVDATA_CIQ_NVDATA_RESET_OFFSET = 524,

	LGE_NVDATA_HARD_RESET_OFFSET = 526, 

	LGE_NVDATA_RTC_INIT_OFFSET = 528,
	LGE_NVDATA_FRSTSTATUS3_OFFSET = 530,

	LGE_NVDATA_910K_DETECT_OFFSET	= 1024,

	LGE_NVDATA_QEM_OFFSET			= 2048,
	LGE_NVDATA_DEVICETEST_OFFSET	= 2052,
	LGE_NVDATA_DEVICDTEST_DATE_OFFSET = 2060,

	LGE_NVDATA_MUIC_RETENTION_OFFSET = 2560,

	LGE_NVDATA_SMPL_EN_OFFSET	= 2570,
	LGE_NVDATA_SMPL_COUNT_OFFSET	= 2572,

	LGE_NVDATA_WEB_DOWNLOAD_OFFSET1 = 2580,
	LGE_NVDATA_WEB_DOWNLOAD_OFFSET2 = 2582,

	LGE_NVDATA_CHARGING_TEMP_OFFSET	= 2600,
	LGE_NVDATA_CONSOLE_MODE_OFFSET = 2604,

	LGE_NVDATA_PROXIMITY_CROSS_TALK_CALIBRATION_OFFSET	= 2700,
	LGE_NVDATA_RIL_RECOVERY_MODE_OFFSET	= 2704,
	LGE_NVDATA_PROXIMITY_PPCOUNT_OFFSET	= 2708,
	
	LGE_NVDATA_MAX_FASTBOOT_OFFSET = 4096,
	LGE_NVDATA_ATKCAL_RED_OFFSET = 4865,
	LGE_NVDATA_ATKCAL_GREEN_OFFSET = 4881,
	LGE_NVDATA_ATKCAL_BLUE_OFFSET = 4897,
}lge_nvdata_offset;

// Value define for nv data
#define LGE_NVDATA_RESET_CAUSE_VAL_USER_RESET	0x94
#define LGE_NVDATA_RESET_CAUSE_VAL_AP_CRASH		0xDE
#define LGE_NVDATA_RESET_CAUSE_VAL_CP_CRASH		0xAD
#define LGE_NVDATA_RESET_CAUSE_FACTORY_RESET	0x46

#define LGE_NVDATA_RESET_CAUSE_WEB_DOWNLOAD_RESET1	0x11
#define LGE_NVDATA_RESET_CAUSE_WEB_DOWNLOAD_RESET2	0x22

#define LGE_NDATA_CRASH_DUMP_INITIAL_VALUE	0x00
#define LGE_NDATA_CRASH_DUMP_ENABLE_VALUE	0xA5
#define LGE_NDATA_CRASH_DUMP_DISABLE_VALUE	0xB3


#define LGE_NVDATA_EMMC_ERR_SIZE_TOO_SMALL	-1;  
#define LGE_NVDATA_EMMC_ERR_SIZE_TOO_LARGE	-2; 

extern int lge_nvdata_read(lge_nvdata_offset offset, char* buf, int size);
extern int lge_nvdata_write(lge_nvdata_offset offset, char* buf, int size);

#endif /* __MACH_TEGRA_X3_NV_H */
